version: '3'
services:
  web:
    # Replace <YOUR_GITHUB_USERNAME> with your actual GitHub username or organization
    image: ghcr.io/Tomkoooo/boathungaryhu:latest
    ports:
      - "6060:3000"
    restart: always
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_TO=${SMTP_TO}

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: http web:3000
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      - web
